### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by thasner** [palantir/eclipse-typescript#215]
``` javascript
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'slate-testlib'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-testlib"]}
TypeError: Cannot read property 'declarations' of undefined
    at hasVisibleDeclarations (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:11225:34)
    at Object.isEntityNameVisible (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:11261:20)
    at emitEntityName (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:7740:49)
    at emitTypeReference (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:7756:17)
    at emitType (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:7716:28)
    at writeReturnTypeAtSignature (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:7671:17)
    at emitSignatureDeclaration (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:8256:17)
    at emitFunctionDeclaration (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:8221:17)
    at emitNode (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:8356:28)
    at emitLines (/Applications/eclipse/plugins/com.palantir.typescript_1.4.0.v20141202-1442/bin/bridge.js:7679:17)
Errors running builder 'TSLint Project Builder' on project 'slate-module-test'.
java.io.FileNotFoundException: /Users/thasner/git/slate/generator-slate-module/test/.tmp/slate-module-test/../config/tslint.json (No such file or directory)
```

**Comment by stevenfan** [comment]
As of 1.5.0.v20150222-2050, this still occurs:

```
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'slate-core'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-core"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-timeline'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-timeline"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-table'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-table"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-slider'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-slider"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-native'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-native"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-multiselect-box'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-multiselect-box"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-markdown'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-markdown"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-map'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-map"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-graph'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-graph"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-dropdown'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-dropdown"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-date-picker'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-date-picker"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-chart'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-chart"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-module-action-button'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-module-action-button"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
Errors running builder 'TypeScript Builder' on project 'slate-app'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-app"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
```
