### ISSUE TITLE
ScriptElementKind missing "type" (and "const" is wrong)

### ISSUE THREAD

**Issue by tbenbrahim** [palantir/eclipse-typescript#223]
dot completion works, Ctrl-Space does not:
As a test, I type `viewp`, to complete `viewport` variable declared on previous line, not sure why the language service returned so much information.

The full text of the language service response is too long for github and is available at https://drive.google.com/file/d/0B0hwaTyOEcSIRVNaVmFYVndsZEk/view?usp=sharing

Extract below, with stack trace:

`java.lang.RuntimeException: Error parsing result: {"entries":[{"name":"page","kind":"parameter","kindModifiers":"","displayParts":[{"text":"(","kind":"punctuation"},{"text":"parameter","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"page","kind":"parameterName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"PDFPageProxy","kind":"interfaceName"}],"documentation":[]},`

... content removed....

`{"name":"RaphaelMatrix","kind":"interface","kindModifiers":"declare","displayParts":[{"text":"interface","kind":"keyword"},{"text":" ","kind":"space"},{"text":"RaphaelMatrix","kind":"interfaceName"}],"documentation":[]},{"name":"RaphaelStatic","kind":"interface","kindModifiers":"declare","displayParts":[{"text":"interface","kind":"keyword"},{"text":" ","kind":"space"},{"text":"RaphaelStatic","kind":"interfaceName"}],"documentation":[]},{"name":"Raphael","kind":"var","kindModifiers":"declare","displayParts":[{"text":"(","kind":"punctuation"},{"text":"var","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"Raphael","kind":"localName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"RaphaelStatic","kind":"interfaceName"}],"documentation":[]},{"name":"ILayoutManager","kind":"interface","kindModifiers":"declare","displayParts":[{"text":"interface","kind":"keyword"},{"text":" ","kind":"space"},{"text":"ILayoutManager","kind":"interfaceName"}],"documentation":[]},{"name":"ILoadMaskService","kind":"interface","kindModifiers":"declare","displayParts":[{"text":"interface","kind":"keyword"},{"text":" ","kind":"space"},{"text":"ILoadMaskService","kind":"interfaceName"}],"documentation":[]},{"name":"CommonDialogCallback","kind":"type","kindModifiers":"declare","displayParts":[{"text":"type","kind":"keyword"},{"text":" ","kind":"space"},{"text":"CommonDialogCallback","kind":"aliasName"},{"text":" ","kind":"space"},{"text":"=","kind":"operator"},{"text":" ","kind":"space"},{"text":"(","kind":"punctuation"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"=>","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"void","kind":"keyword"}],"documentation":[]},{"name":"CommonDialogConfirmCallback","kind":"type","kindModifiers":"declare","displayParts":[{"text":"type","kind":"keyword"},{"text":" ","kind":"space"},{"text":"CommonDialogConfirmCallback","kind":"aliasName"},{"text":" ","kind":"space"},{"text":"=","kind":"operator"},{"text":" ","kind":"space"},{"text":"(","kind":"punctuation"},{"text":"status","kind":"parameterName"},{"text":":","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"boolean","kind":"keyword"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"=>","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"void","kind":"keyword"}],"documentation":[]},{"name":"ICommonDialogs","kind":"interface","kindModifiers":"declare","displayParts":[{"text":"interface","kind":"keyword"},{"text":" ","kind":"space"},{"text":"ICommonDialogs","kind":"interfaceName"}],"documentation":[]},{"name":"undefined","kind":"var","kindModifiers":"","displayParts":[{"text":"(","kind":"punctuation"},{"text":"var","kind":"text"},{"text":")","kind":"punctuation"},{"text":" ","kind":"space"},{"text":"undefined","kind":"propertyName"}],"documentation":[]}],"memberCompletion":false}
	at com.palantir.typescript.services.Bridge.call(Bridge.java:104)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.getCompletionsAtPosition(LanguageEndpoint.java:171)
	at com.palantir.typescript.text.FileLanguageService.getCompletionsAtPosition(FileLanguageService.java:83)
	at com.palantir.typescript.text.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:85)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1839)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:566)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:563)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:498)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:492)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1665)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:932)
	at com.palantir.typescript.text.TypeScriptSourceViewer.doOperation(TypeScriptSourceViewer.java:68)
	at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:82)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:80)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:119)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:285)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:504)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:555)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:376)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:322)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:84)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1104)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1525)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4723)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:344)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4611)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4977)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.palantir.typescript.services.language.ScriptElementKind from String value 'type': value not one of declared Enum instance names
 at [Source: java.io.StringReader@30aa7eea; line: 1, column: 858459]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:626)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:91)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:20)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:449)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:347)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:976)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:230)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:207)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:449)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:347)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:976)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:102)
	... 74 more`

**Comment by derekcicerone** [comment]
Thanks for the thorough repro info. Looks like this is the culprit:
```
Can not construct instance of com.palantir.typescript.services.language.ScriptElementKind from String value 'type': value not one of declared Enum instance names at [Source: java.io.StringReader@30aa7eea; line: 1, column: 858459]
```

Did this error occur with the latest 1.4 release of the plugin?

**Comment by tbenbrahim** [comment]
Latest version, started with Typescript last week, so I do not know if this is a regression:
This is the entry at col 86453
`{"name":"CommonDialogCallback","kind":"type","kindModifiers":"declare","displayParts":[{"text":"type","kind":"keyword"}`

the line of code this comes from is one of the first two:
```typescript
declare type CommonDialogCallback=() => void;
declare type CommonDialogConfirmCallback=(status: boolean) => void;
interface ICommonDialogs {
    alert(message: string, title: string, callback?: CommonDialogCallback): void;
    info(message: string, title: string, callback?: CommonDialogCallback): void;
    warn(message: string, title: string, callback?: CommonDialogCallback): void;
    error(message: string, title: string, callback?: CommonDialogCallback): void;
    confirm(message: string, title: string, confirmButtonText: string, callback: CommonDialogConfirmCallback): void;
}
```
I refactored to :
```typescript
//declare type CommonDialogCallback=() => void;
//declare type CommonDialogConfirmCallback=(status: boolean) => void;

interface ICommonDialogs {
    alert(message: string, title: string, callback?: () => void): void;
    info(message: string, title: string, callback?: () => void): void;
    warn(message: string, title: string, callback?: () => void): void;
    error(message: string, title: string, callback?: () => void): void;
    confirm(message: string, title: string, confirmButtonText: string, callback: (status: boolean) => void): void;
}
```
and ctrl-space completion works again. Looks like the declare keyword is not supported yet by the plugin.

**Comment by derekcicerone** [comment]
Great catch, sorry about that. I've pushed a fix which should be available within 15 mins.

**Comment by tbenbrahim** [comment]
Thank you for the quick fix and great plugin
