### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by stevenfan** [palantir/eclipse-typescript#232]
On 1.5.0.v20150222-2050, I get this exception while building:

```
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'slate-core'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-core"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:1174:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4491:22)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:4504:9)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26065:44)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26127:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:26466:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20958:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20922:27)
	at processRootFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20910:13)
	at /Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150222-2050/bin/bridge.js:20811:56
```

**Comment by Palmer-JC** [comment]
I am getting a very similar error, pasted at bottom.  If I figure out how to add source files in a few at a time, I can get it to build,  but just did a clean.  Have to do it again.

Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'Dialog'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["Dialog"]}
Error: Debug Failure. False expression: 
	at Object.assert (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:1164:23)
	at checkChangeRange (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:4340:22)
	at Object.updateSourceFile (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:4353:9)
	at updateLanguageServiceSourceFile (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:24789:44)
	at Object.updateDocument (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:24851:32)
	at Object.getOrCreateSourceFile [as getSourceFile] (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:25128:49)
	at findSourceFile (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:20245:62)
	at processSourceFile (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:20209:27)
	at processRootFile (/home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:20197:13)
	at /home/jeff/.eclipse/org.eclipse.platform_4.4.1_1473617060_linux_gtk_x86_64/plugins/com.palantir.typescript_1.5.0.v20150215-1520/bin/bridge.js:20098:56

**Comment by derekcicerone** [comment]
Thanks for the report Jeff. Do you know what steps you took to reproduce the issue? I've seen it as well but getting it to reproduce is proving tricky.

This is also the develop version of the plugin which means the bug could actually be in TypeScript itself (since 1.5 hasn't released yet). If you aren't using any of the new functionality it might be possible to downgrade to workaround this for now.

**Comment by Palmer-JC** [comment]
I wish I knew.  Am going back to 1.4 of plugin. I did not know I was running test.  Need to rip out that pointer to pre-production.

  I can no-longer get the thing to build, even pieces added in at a time.  I can always reproduce.  This will eventually be in Github, but not ready yet.  Can zip as is, if you need reliable reproduction.

This is a newish project built on top of others, so using many d.ts.  Am also building a base class, then sub-classing in the same project.  The only thing can think of.

**Comment by derekcicerone** [comment]
Sorry for the inconvenience. My suspicion is that it's a bug in TypeScript itself, but I've had trouble pinning down repro steps so it's hard to file a bug without them.

**Comment by derekcicerone** [comment]
I believe this was related to https://github.com/Microsoft/TypeScript/pull/2167. If you still see this issue after updating to the latest 1.5 release, please let me know.
