### ISSUE TITLE
The node process has crashed

### ISSUE THREAD

**Issue by pofuk** [palantir/eclipse-typescript#237]
Hi!

I downloaded Eclipse Stadard 4.4, checked out code from repo. I Go right click, debug as Eclipse Application on com.palantir.typescript project an I get this error in new Eclipse:

![image](https://cloud.githubusercontent.com/assets/2906197/6709954/934dfa16-cd7d-11e4-8167-33ec794ebe96.png)

STACK TRACE: 
```

!ENTRY org.eclipse.core.resources 4 75 2015-03-18 14:44:19.234
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.core.resources 4 75 2015-03-18 14:44:19.235
!MESSAGE Error instantiating builder 'com.palantir.typescript.typeScriptBuilder'.
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in "com.palantir.typescript" was unable to instantiate class "com.palantir.typescript.TypeScriptBuilder".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:186)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:907)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:860)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:545)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:574)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.setLibContents(LanguageEndpoint.java:341)
	at com.palantir.typescript.services.language.LanguageEndpoint.<init>(LanguageEndpoint.java:62)
	at com.palantir.typescript.TypeScriptPlugin.getBuilderLanguageEndpoint(TypeScriptPlugin.java:115)
	at com.palantir.typescript.TypeScriptBuilder.<init>(TypeScriptBuilder.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	... 16 more
!SUBENTRY 2 org.eclipse.equinox.registry 4 1 2015-03-18 14:44:19.236
!MESSAGE Plug-in "com.palantir.typescript" was unable to instantiate class "com.palantir.typescript.TypeScriptBuilder".
!STACK 0
java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.setLibContents(LanguageEndpoint.java:341)
	at com.palantir.typescript.services.language.LanguageEndpoint.<init>(LanguageEndpoint.java:62)
	at com.palantir.typescript.TypeScriptPlugin.getBuilderLanguageEndpoint(TypeScriptPlugin.java:115)
	at com.palantir.typescript.TypeScriptBuilder.<init>(TypeScriptBuilder.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:907)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:860)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:545)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:574)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2015-03-18 14:44:19.237
!MESSAGE Plug-in "com.palantir.typescript" was unable to instantiate class "com.palantir.typescript.TypeScriptBuilder".
!STACK 0
java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.setLibContents(LanguageEndpoint.java:341)
	at com.palantir.typescript.services.language.LanguageEndpoint.<init>(LanguageEndpoint.java:62)
	at com.palantir.typescript.TypeScriptPlugin.getBuilderLanguageEndpoint(TypeScriptPlugin.java:115)
	at com.palantir.typescript.TypeScriptBuilder.<init>(TypeScriptBuilder.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:907)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:860)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:545)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:574)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
c
!ENTRY org.eclipse.core.resources 4 75 2015-03-18 14:46:23.992
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.core.resources 4 75 2015-03-18 14:46:23.992
!MESSAGE Error instantiating builder 'com.palantir.typescript.typeScriptBuilder'.
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in "com.palantir.typescript" was unable to instantiate class "com.palantir.typescript.TypeScriptBuilder".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:186)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:907)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:860)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:545)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:574)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.setLibContents(LanguageEndpoint.java:341)
	at com.palantir.typescript.services.language.LanguageEndpoint.<init>(LanguageEndpoint.java:62)
	at com.palantir.typescript.TypeScriptPlugin.getBuilderLanguageEndpoint(TypeScriptPlugin.java:115)
	at com.palantir.typescript.TypeScriptBuilder.<init>(TypeScriptBuilder.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	... 16 more
!SUBENTRY 2 org.eclipse.equinox.registry 4 1 2015-03-18 14:46:23.993
!MESSAGE Plug-in "com.palantir.typescript" was unable to instantiate class "com.palantir.typescript.TypeScriptBuilder".
!STACK 0
java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.setLibContents(LanguageEndpoint.java:341)
	at com.palantir.typescript.services.language.LanguageEndpoint.<init>(LanguageEndpoint.java:62)
	at com.palantir.typescript.TypeScriptPlugin.getBuilderLanguageEndpoint(TypeScriptPlugin.java:115)
	at com.palantir.typescript.TypeScriptBuilder.<init>(TypeScriptBuilder.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:907)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:860)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:545)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:574)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2015-03-18 14:46:23.994
!MESSAGE Plug-in "com.palantir.typescript" was unable to instantiate class "com.palantir.typescript.TypeScriptBuilder".
!STACK 0
java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:83)
	at com.palantir.typescript.services.language.LanguageEndpoint.setLibContents(LanguageEndpoint.java:341)
	at com.palantir.typescript.services.language.LanguageEndpoint.<init>(LanguageEndpoint.java:62)
	at com.palantir.typescript.TypeScriptPlugin.getBuilderLanguageEndpoint(TypeScriptPlugin.java:115)
	at com.palantir.typescript.TypeScriptBuilder.<init>(TypeScriptBuilder.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.core.internal.events.BuildManager.instantiateBuilder(BuildManager.java:907)
	at org.eclipse.core.internal.events.BuildManager.initializeBuilder(BuildManager.java:860)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:545)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:574)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:244)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```

**Comment by derekcicerone** [comment]
I think you may have to run "grunt" to build the bridge before launching the app to debug it.

**Comment by derekcicerone** [comment]
Some notes on development can be found here:
https://github.com/palantir/eclipse-typescript/wiki

**Comment by pofuk** [comment]
Sorry! My mistake. Misconfigured grunt.
