### ISSUE TITLE
Builder throws exception related to bad file changes

### ISSUE THREAD

**Issue by thasner** [palantir/eclipse-typescript#250]
```
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'slate-app'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["slate-app"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:1364:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:10608:26)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:10251:13)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:6310:34)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:36653:44)
	at acquireOrUpdateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:36725:40)
	at Object.acquireDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:36702:20)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:37243:41)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:29872:62)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.5.0.v20150513-1700/bin/bridge.js:29833:27)
```

**Comment by derekcicerone** [comment]
Please try rebooting eclipse.

**Comment by derekcicerone** [comment]
Unclear if this is a regression in TypeScript itself or the plug-in. Given that nothing has changed in the plug-in, my suspicion is the TypeScript language services.

**Comment by thasner** [comment]
rebooting has stopped the error from occurring.  thanks!

**Comment by derekcicerone** [comment]
just updated to TypeScript 1.5 - please let me know if this issue happens again.
