### ISSUE TITLE
eclipse error

### ISSUE THREAD

**Issue by thasner** [palantir/eclipse-typescript#279]
```
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'compass'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["compass-app"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:1558:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:12735:26)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:12372:13)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:7571:34)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43010:44)
	at acquireOrUpdateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43097:40)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43076:20)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43694:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:35791:33)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:35745:27)
Errors running builder 'TypeScript Builder' on project 'compass-app'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"getAllDiagnostics","arguments":["compass-app"]}
Error: Debug Failure. False expression: 
	at Object.assert (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:1558:23)
	at checkChangeRange (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:12735:26)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:12372:13)
	at Object.updateSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:7571:34)
	at updateLanguageServiceSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43010:44)
	at acquireOrUpdateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43097:40)
	at Object.updateDocument (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43076:20)
	at Object.getOrCreateSourceFile [as getSourceFile] (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:43694:49)
	at findSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:35791:33)
	at processSourceFile (/Applications/eclipse/plugins/com.palantir.typescript_1.6.0.v20150911-1832/bin/bridge.js:35745:27)
```

**Comment by derekcicerone** [comment]
Looks like a bug in TypeScript itself. Might not be much we can do about this one :/

**Comment by basarat** [comment]
Disclaimer : the following is purely anecdotal and just for hopeful usefulness :rose: 

I used to get this error from time to time ... it generally turned out to be the language service model of the `.ts` file being different from the version I had in my code's memory ... and then when typescript asks for script snapshot *getChanges* it would find them to be different then what it expected. Also this happened mostly due to newline handling.

**Comment by derekcicerone** [comment]
Thanks for the tip! Ugh, that's what I was most afraid of - those types of bugs are usually pretty hard to track down. Will have to see if we get better repro steps.

**Comment by HiaslTiasl** [comment]
I solved the issue by mapping `.ts` files to the correct character encoding in Preferences > General > Content Types.

All of my `.ts` files are copies of original `.js` files which I wanted to port to TypeScript. These `.js` files are encoded in UTF-8, hence the `.ts` files are UTF-8, too. However, without linking them to a Content-Type in Eclipse, they are interpreted using the machine's default encoding, which differs from UTF-8.

The different encodings then yield in different character counts, which causes the assertion to fail.

**Comment by derekcicerone** [comment]
Cool, curious to learn more about this fix. Was the default encoding not UTF-8 already?

**Comment by HiaslTiasl** [comment]
No, the default encoding was ANSI on a german Windows 10 machine. I wanted to define a content type for TypeScript but didn't find a way for doing so in Eclipse. Therefore, I associated `*.ts` files to the JavaScript content type in order to map them to the right encoding.

It's maybe also important to say that my files contain german comments with special characters, which are likely to cause the issue
