### ISSUE TITLE
Error: ENOENT, no such file or directory '(workspaceloc)\WORKSPACE_LOC\(myfile).ts'

### ISSUE THREAD

**Issue by mttcr** [palantir/eclipse-typescript#283]
Hello,
I referenced a file from another project in the workspace, and I have the following error.
```
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'test2'.
The following request caused an error to be thrown:
{"endpoint":"language","method":"updateFiles","arguments":[[{"delta":"ADDED","fileName":"eclipse:/test2/src/test1.ts","filePath":"WORKSPACE_LOC\\test1\\src\\test1.ts"},{"delta":"ADDED","fileName":"eclipse:/test2/src/test2.ts","filePath":"C:\\(workspace)\\test2\\src\\test2.ts"}]]}
Error: ENOENT, no such file or directory 'C:\_(eclipse)_\WORKSPACE_LOC\test1\src\test1.ts'
	at Error (native)
	at Object.fs.openSync (fs.js:500:18)
	at Object.fs.readFileSync (fs.js:352:15)
	at readFileContents (C:\_(eclipse)_\plugins\com.palantir.typescript_1.6.0.v20150930-1942\bin\bridge.js:49821:19)
	at C:\_(eclipse)_\plugins\com.palantir.typescript_1.6.0.v20150930-1942\bin\bridge.js:49748:44
	at Array.forEach (native)
	at LanguageEndpoint.updateFiles (C:\_(eclipse)_\plugins\com.palantir.typescript_1.6.0.v20150930-1942\bin\bridge.js:49734:20)
	at Main.processRequest (C:\_(eclipse)_\plugins\com.palantir.typescript_1.6.0.v20150930-1942\bin\bridge.js:49865:37)
	at Interface.<anonymous> (C:\_(eclipse)_\plugins\com.palantir.typescript_1.6.0.v20150930-1942\bin\bridge.js:49854:23)
	at Interface.emit (events.js:107:17)
```
Looks like the variable WORKSPACE_LOC is not translated.
To reproduce, create a file like that:
![image](https://cloud.githubusercontent.com/assets/8974534/10241410/d8c4d2ac-68e8-11e5-814f-47a3273e7892.png)

**Comment by derekcicerone** [comment]
Cross-project file references aren't really supported. Depending upon the module system, it may be possible to support it someday, but its a fairly complicated feature (if it even makes sense).
