### ISSUE TITLE
Completions failing

### ISSUE THREAD

**Issue by nealeu** [palantir/eclipse-typescript#294]
Completions are working rather erratically for me (actually for some weeks, but I've just been ploughing on, until today when I bothered to check the error logs).

Here's what's getting reported: 

```
java.lang.RuntimeException: The following request caused an error to be thrown:
{"endpoint":"language","method":"getCompletionsAtPosition","arguments":["ecco-offline","eclipse:/ecco-offline/src/main/resources/com/ecco/offline/staticFiles/scripts/evidence/my-plan/MyPlanControl.ts",2928]}
TypeError: Cannot read property 'parent' of undefined
	at appendOuterTypeParameters (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:15314:28)
	at getOuterTypeParametersOfClassOrInterface (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:15331:20)
	at getTypeParametersOfClassOrInterface (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:15352:35)
	at appendParentTypeArgumentsAndSymbolName (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:14226:75)
	at walkSymbol (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:14268:29)
	at Object.buildSymbolDisplay (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:14278:21)
	at /home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:39148:51
	at mapToDisplayParts (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:39134:9)
	at Object.symbolToDisplayParts (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:39147:16)
	at addFullSymbolName (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.6.0.v20151006-2355/bin/bridge.js:45157:49)
```

**Comment by derekcicerone** [comment]
Looks like a bug in the TypeScript language services. With the recent upgrade to 1.7 perhaps this was fixed? Could you try upgrading?

**Comment by nealeu** [comment]
Hi,

I've updated to 1.7, and the same bug seems to still be there:

```
The following request caused an error to be thrown:
{"endpoint":"language","method":"getCompletionsAtPosition","arguments":["ecco-offline","eclipse:/ecco-offline/src/main/resources/com/ecco/offline/staticFiles/scripts/evidence/tabular/SmartStepControl.ts",8437]}
TypeError: Cannot read property 'parent' of undefined
	at appendOuterTypeParameters (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:15716:28)
	at getOuterTypeParametersOfClassOrInterface (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:15733:20)
	at getTypeParametersOfClassOrInterface (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:15754:35)
	at appendParentTypeArgumentsAndSymbolName (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:14612:75)
	at walkSymbol (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:14654:29)
	at Object.buildSymbolDisplay (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:14664:21)
	at /home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:39999:51
	at mapToDisplayParts (/home/neale/apps/sts/sts-3.7.0.RELEASE/plugins/com.palantir.typescript_1.7.0.v20151201-1631/bin/bridge.js:39985:9)
```

**Comment by derekcicerone** [comment]
Bummer, you could also try the develop branch of the plugin (its on the latest TypeScript master code which is likely to be the 1.8 release). If that doesn't work, this will need to be reported to the TypeScript team since the bug is in that part of the codebase from what I can see in the above stack traces.
