### ISSUE TITLE
NullPointerException on multi module project

### ISSUE THREAD

**Issue by david-bouyssie** [palantir/eclipse-typescript#296]
I'm currently using your great plugin on a multi module project.
I configured my parent and child project to compile TS files.
Eclipse rises Exception when it tries to list resources to be compiled.
It seems that filed located in the child project are searched in the resources of the parent project and are not found.
As a workaround I'm currently closing my parent project because most of my developments are done in the child project.
I guess that the returned value of the call to "com.palantir.typescript.EclipseResources.getFilePath" could be checked for nullity to avoid this error. But maybe you will have a more appropriate fix to this issue.

Here is the stack trace:

```
java.lang.NullPointerException
	at com.palantir.typescript.EclipseResources.getFilePath(EclipseResources.java:76)
	at com.palantir.typescript.services.language.LanguageEndpoint.getFiles(LanguageEndpoint.java:334)
	at com.palantir.typescript.services.language.LanguageEndpoint.initializeProjectTree(LanguageEndpoint.java:321)
	at com.palantir.typescript.services.language.LanguageEndpoint.initializeProjectTree(LanguageEndpoint.java:307)
	at com.palantir.typescript.services.language.LanguageEndpoint.initializeProject(LanguageEndpoint.java:77)
	at com.palantir.typescript.TypeScriptBuilder.startupOnInitialize(TypeScriptBuilder.java:120)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:549)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:575)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:243)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by derekcicerone** [comment]
Hmm interesting. I haven't seen anything like this before - any idea why the files may not be found. It looks like it is failing when attempting to resolve the actual operating system file path name.

**Comment by david-bouyssie** [comment]
My opinion is that the relative path of the TS file located in the child project in searched in the parent project. Thus it leads to a wrong absolute path location.

**Comment by derekcicerone** [comment]
Hmm ok. Unfortunately I don't think I have enough information to further diagnose this from here. Is your project open source by any chance?

**Comment by david-bouyssie** [comment]
Unfortunately not yet...
But maybe I could try to make a simple example.
I'm developing a web app using the Play Framework (the Scala version).
I can try to create a project from scratch with a parent and a child project as a starting point.

**Comment by david-bouyssie** [comment]
I close this issue because it seems to be solved.
