### ISSUE TITLE
Error using moduleResolution = 'node' in tsconfig file

### ISSUE THREAD

**Issue by diogosantana** [palantir/eclipse-typescript#345]
The build fails after select 'Use tsconfig' preference for tsconfig like this:

`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}
`

Exception:

`
java.lang.IllegalArgumentException: No enum constant com.palantir.typescript.services.language.ModuleResolutionKind.NODE
	at java.lang.Enum.valueOf(Unknown Source)
	at com.palantir.typescript.services.language.ModuleResolutionKind.valueOf(ModuleResolutionKind.java:1)
	at com.palantir.typescript.services.language.CompilerOptions.fromProject(CompilerOptions.java:207)
	at com.palantir.typescript.services.language.LanguageEndpoint.initializeProjectTree(LanguageEndpoint.java:318)
	at com.palantir.typescript.services.language.LanguageEndpoint.initializeProject(LanguageEndpoint.java:77)
	at com.palantir.typescript.TypeScriptBuilder.startupOnInitialize(TypeScriptBuilder.java:119)
	at org.eclipse.core.internal.events.BuildManager.getBuilder(BuildManager.java:550)
	at org.eclipse.core.internal.events.BuildManager.getRule(BuildManager.java:1145)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:545)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:120)
	at com.palantir.typescript.Builders$1.run(Builders.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
`

The ModuleResolutionKind enum accepts CLASSIC and NODE_JS, while typescript's compiler accepts 
"Classic" or "Node" (https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by sixinli** [comment]
will take a look if we can just swap that to "node" in a bit :)
