### ISSUE TITLE
IllegalStateException: The node process has crashed.

### ISSUE THREAD

**Issue by fljmayer** [palantir/eclipse-typescript#354]
I have a pristine Angular application that was generated with just 'ng new "projectName"'. I am using Node 6.10.2. When I try to open a .ts file in Eclipse, most of them produce just this exception:
`java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.classifier.Classifier.getClassificationsForLines(Classifier.java:50)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.classifyLines(PresentationReconciler.java:247)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.createPresentation(PresentationReconciler.java:217)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.processEvent(PresentationReconciler.java:122)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.access$0(PresentationReconciler.java:119)
	at com.palantir.typescript.text.reconciler.PresentationReconciler$MyTextListener.textChanged(PresentationReconciler.java:305)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2699)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3320)
	at org.eclipse.jface.text.TextViewer.initializeWidgetContents(TextViewer.java:3368)
	at org.eclipse.jface.text.TextViewer.setVisibleDocument(TextViewer.java:3407)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2795)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:634)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:584)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3995)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3465)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:55)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:445)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:341)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)`

**Comment by forrests123** [comment]
Did you find the solution to this issue?

**Comment by Rouche** [comment]
https://nodejs.org/en/download/

Latest LTS Version: 16.14.0 (includes npm 8.3.1)

I no longer use Eclipse so no time to update plugin. IntelliJ is always up to date.

Clone my repo, update node JS to latest and rebuild. Use your own repository when you install.

Good luck!
